// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: order.proto

package orderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusRequest, opts ...grpc.CallOption) (*UpdateOrderStatusResponse, error)
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
	// Obtener ordenes por cliente
	GetOrdersByClient(ctx context.Context, in *GetOrdersByClientRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error)
	// Obtener ordenes por restaurante
	GetOrdersByRestaurant(ctx context.Context, in *GetOrdersByRestaurantRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error)
	// Asignar repartidor
	AssignDriver(ctx context.Context, in *AssignDriverRequest, opts ...grpc.CallOption) (*AssignDriverResponse, error)
	GetFinishedOrders(ctx context.Context, in *GetFinishedOrdersRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error)
	GetDeliveredOrders(ctx context.Context, in *GetDeliveredOrdersRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error)
	GetCancelledOrRejectedOrders(ctx context.Context, in *GetCancelledOrdersRequest, opts ...grpc.CallOption) (*GetCancelledOrRejectedOrdersResponse, error)
	GetOrdersByDriver(ctx context.Context, in *GetOrdersByDriverRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error)
	// Agregar imagen a la orden
	AddOrderImage(ctx context.Context, in *AddOrderImageRequest, opts ...grpc.CallOption) (*AddOrderImageResponse, error)
	GetOrderImage(ctx context.Context, in *GetOrderImageRequest, opts ...grpc.CallOption) (*GetOrderImageResponse, error)
	GetTopRestaurantsByOrders(ctx context.Context, in *GetTopRestaurantsByOrdersRequest, opts ...grpc.CallOption) (*GetTopRestaurantsByOrdersResponse, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) UpdateOrderStatus(ctx context.Context, in *UpdateOrderStatusRequest, opts ...grpc.CallOption) (*UpdateOrderStatusResponse, error) {
	out := new(UpdateOrderStatusResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/UpdateOrderStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	out := new(CancelOrderResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/CancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrdersByClient(ctx context.Context, in *GetOrdersByClientRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error) {
	out := new(GetOrdersResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/GetOrdersByClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrdersByRestaurant(ctx context.Context, in *GetOrdersByRestaurantRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error) {
	out := new(GetOrdersResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/GetOrdersByRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) AssignDriver(ctx context.Context, in *AssignDriverRequest, opts ...grpc.CallOption) (*AssignDriverResponse, error) {
	out := new(AssignDriverResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/AssignDriver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetFinishedOrders(ctx context.Context, in *GetFinishedOrdersRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error) {
	out := new(GetOrdersResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/GetFinishedOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetDeliveredOrders(ctx context.Context, in *GetDeliveredOrdersRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error) {
	out := new(GetOrdersResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/GetDeliveredOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetCancelledOrRejectedOrders(ctx context.Context, in *GetCancelledOrdersRequest, opts ...grpc.CallOption) (*GetCancelledOrRejectedOrdersResponse, error) {
	out := new(GetCancelledOrRejectedOrdersResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/GetCancelledOrRejectedOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrdersByDriver(ctx context.Context, in *GetOrdersByDriverRequest, opts ...grpc.CallOption) (*GetOrdersResponse, error) {
	out := new(GetOrdersResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/GetOrdersByDriver", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) AddOrderImage(ctx context.Context, in *AddOrderImageRequest, opts ...grpc.CallOption) (*AddOrderImageResponse, error) {
	out := new(AddOrderImageResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/AddOrderImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrderImage(ctx context.Context, in *GetOrderImageRequest, opts ...grpc.CallOption) (*GetOrderImageResponse, error) {
	out := new(GetOrderImageResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/GetOrderImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetTopRestaurantsByOrders(ctx context.Context, in *GetTopRestaurantsByOrdersRequest, opts ...grpc.CallOption) (*GetTopRestaurantsByOrdersResponse, error) {
	out := new(GetTopRestaurantsByOrdersResponse)
	err := c.cc.Invoke(ctx, "/order.OrderService/GetTopRestaurantsByOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations should embed UnimplementedOrderServiceServer
// for forward compatibility
type OrderServiceServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	UpdateOrderStatus(context.Context, *UpdateOrderStatusRequest) (*UpdateOrderStatusResponse, error)
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	// Obtener ordenes por cliente
	GetOrdersByClient(context.Context, *GetOrdersByClientRequest) (*GetOrdersResponse, error)
	// Obtener ordenes por restaurante
	GetOrdersByRestaurant(context.Context, *GetOrdersByRestaurantRequest) (*GetOrdersResponse, error)
	// Asignar repartidor
	AssignDriver(context.Context, *AssignDriverRequest) (*AssignDriverResponse, error)
	GetFinishedOrders(context.Context, *GetFinishedOrdersRequest) (*GetOrdersResponse, error)
	GetDeliveredOrders(context.Context, *GetDeliveredOrdersRequest) (*GetOrdersResponse, error)
	GetCancelledOrRejectedOrders(context.Context, *GetCancelledOrdersRequest) (*GetCancelledOrRejectedOrdersResponse, error)
	GetOrdersByDriver(context.Context, *GetOrdersByDriverRequest) (*GetOrdersResponse, error)
	// Agregar imagen a la orden
	AddOrderImage(context.Context, *AddOrderImageRequest) (*AddOrderImageResponse, error)
	GetOrderImage(context.Context, *GetOrderImageRequest) (*GetOrderImageResponse, error)
	GetTopRestaurantsByOrders(context.Context, *GetTopRestaurantsByOrdersRequest) (*GetTopRestaurantsByOrdersResponse, error)
}

// UnimplementedOrderServiceServer should be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (UnimplementedOrderServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderServiceServer) UpdateOrderStatus(context.Context, *UpdateOrderStatusRequest) (*UpdateOrderStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrderStatus not implemented")
}
func (UnimplementedOrderServiceServer) CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedOrderServiceServer) GetOrdersByClient(context.Context, *GetOrdersByClientRequest) (*GetOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrdersByClient not implemented")
}
func (UnimplementedOrderServiceServer) GetOrdersByRestaurant(context.Context, *GetOrdersByRestaurantRequest) (*GetOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrdersByRestaurant not implemented")
}
func (UnimplementedOrderServiceServer) AssignDriver(context.Context, *AssignDriverRequest) (*AssignDriverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignDriver not implemented")
}
func (UnimplementedOrderServiceServer) GetFinishedOrders(context.Context, *GetFinishedOrdersRequest) (*GetOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFinishedOrders not implemented")
}
func (UnimplementedOrderServiceServer) GetDeliveredOrders(context.Context, *GetDeliveredOrdersRequest) (*GetOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDeliveredOrders not implemented")
}
func (UnimplementedOrderServiceServer) GetCancelledOrRejectedOrders(context.Context, *GetCancelledOrdersRequest) (*GetCancelledOrRejectedOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCancelledOrRejectedOrders not implemented")
}
func (UnimplementedOrderServiceServer) GetOrdersByDriver(context.Context, *GetOrdersByDriverRequest) (*GetOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrdersByDriver not implemented")
}
func (UnimplementedOrderServiceServer) AddOrderImage(context.Context, *AddOrderImageRequest) (*AddOrderImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOrderImage not implemented")
}
func (UnimplementedOrderServiceServer) GetOrderImage(context.Context, *GetOrderImageRequest) (*GetOrderImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderImage not implemented")
}
func (UnimplementedOrderServiceServer) GetTopRestaurantsByOrders(context.Context, *GetTopRestaurantsByOrdersRequest) (*GetTopRestaurantsByOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopRestaurantsByOrders not implemented")
}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_UpdateOrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrderStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).UpdateOrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/UpdateOrderStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).UpdateOrderStatus(ctx, req.(*UpdateOrderStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrdersByClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersByClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrdersByClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/GetOrdersByClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrdersByClient(ctx, req.(*GetOrdersByClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrdersByRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersByRestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrdersByRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/GetOrdersByRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrdersByRestaurant(ctx, req.(*GetOrdersByRestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_AssignDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).AssignDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/AssignDriver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).AssignDriver(ctx, req.(*AssignDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetFinishedOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFinishedOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetFinishedOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/GetFinishedOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetFinishedOrders(ctx, req.(*GetFinishedOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetDeliveredOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeliveredOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetDeliveredOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/GetDeliveredOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetDeliveredOrders(ctx, req.(*GetDeliveredOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetCancelledOrRejectedOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCancelledOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetCancelledOrRejectedOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/GetCancelledOrRejectedOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetCancelledOrRejectedOrders(ctx, req.(*GetCancelledOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrdersByDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrdersByDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrdersByDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/GetOrdersByDriver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrdersByDriver(ctx, req.(*GetOrdersByDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_AddOrderImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrderImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).AddOrderImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/AddOrderImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).AddOrderImage(ctx, req.(*AddOrderImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrderImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrderImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/GetOrderImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrderImage(ctx, req.(*GetOrderImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetTopRestaurantsByOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopRestaurantsByOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetTopRestaurantsByOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.OrderService/GetTopRestaurantsByOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetTopRestaurantsByOrders(ctx, req.(*GetTopRestaurantsByOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
		{
			MethodName: "UpdateOrderStatus",
			Handler:    _OrderService_UpdateOrderStatus_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _OrderService_CancelOrder_Handler,
		},
		{
			MethodName: "GetOrdersByClient",
			Handler:    _OrderService_GetOrdersByClient_Handler,
		},
		{
			MethodName: "GetOrdersByRestaurant",
			Handler:    _OrderService_GetOrdersByRestaurant_Handler,
		},
		{
			MethodName: "AssignDriver",
			Handler:    _OrderService_AssignDriver_Handler,
		},
		{
			MethodName: "GetFinishedOrders",
			Handler:    _OrderService_GetFinishedOrders_Handler,
		},
		{
			MethodName: "GetDeliveredOrders",
			Handler:    _OrderService_GetDeliveredOrders_Handler,
		},
		{
			MethodName: "GetCancelledOrRejectedOrders",
			Handler:    _OrderService_GetCancelledOrRejectedOrders_Handler,
		},
		{
			MethodName: "GetOrdersByDriver",
			Handler:    _OrderService_GetOrdersByDriver_Handler,
		},
		{
			MethodName: "AddOrderImage",
			Handler:    _OrderService_AddOrderImage_Handler,
		},
		{
			MethodName: "GetOrderImage",
			Handler:    _OrderService_GetOrderImage_Handler,
		},
		{
			MethodName: "GetTopRestaurantsByOrders",
			Handler:    _OrderService_GetTopRestaurantsByOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
