// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: user.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password       string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	NombreCompleto string                 `protobuf:"bytes,4,opt,name=nombre_completo,json=nombreCompleto,proto3" json:"nombre_completo,omitempty"`
	Role           string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *User) GetNombreCompleto() string {
	if x != nil {
		return x.NombreCompleto
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GetUserByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByEmailRequest) Reset() {
	*x = GetUserByEmailRequest{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByEmailRequest) ProtoMessage() {}

func (x *GetUserByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetUserByEmailRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetUserByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIDRequest) Reset() {
	*x = GetUserByIDRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIDRequest) ProtoMessage() {}

func (x *GetUserByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIDRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIDRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type CreateUserRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Email          string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password       string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	NombreCompleto string                 `protobuf:"bytes,3,opt,name=nombre_completo,json=nombreCompleto,proto3" json:"nombre_completo,omitempty"`
	Rol            string                 `protobuf:"bytes,4,opt,name=rol,proto3" json:"rol,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetNombreCompleto() string {
	if x != nil {
		return x.NombreCompleto
	}
	return ""
}

func (x *CreateUserRequest) GetRol() string {
	if x != nil {
		return x.Rol
	}
	return ""
}

type CreateUserResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role           string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	NombreCompleto string                 `protobuf:"bytes,4,opt,name=nombre_completo,json=nombreCompleto,proto3" json:"nombre_completo,omitempty"`
	Telefono       string                 `protobuf:"bytes,5,opt,name=telefono,proto3" json:"telefono,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateUserResponse) GetNombreCompleto() string {
	if x != nil {
		return x.NombreCompleto
	}
	return ""
}

func (x *CreateUserResponse) GetTelefono() string {
	if x != nil {
		return x.Telefono
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	RoleFilter    string                 `protobuf:"bytes,3,opt,name=role_filter,json=roleFilter,proto3" json:"role_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *ListUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUsersRequest) GetRoleFilter() string {
	if x != nil {
		return x.RoleFilter
	}
	return ""
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUsersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUsersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CreateDriverRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClienteId     int32                  `protobuf:"varint,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	RepartidorId  int32                  `protobuf:"varint,2,opt,name=repartidor_id,json=repartidorId,proto3" json:"repartidor_id,omitempty"`
	Estrellas     int32                  `protobuf:"varint,3,opt,name=estrellas,proto3" json:"estrellas,omitempty"`
	Comentario    string                 `protobuf:"bytes,4,opt,name=comentario,proto3" json:"comentario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverRatingRequest) Reset() {
	*x = CreateDriverRatingRequest{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverRatingRequest) ProtoMessage() {}

func (x *CreateDriverRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverRatingRequest.ProtoReflect.Descriptor instead.
func (*CreateDriverRatingRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *CreateDriverRatingRequest) GetClienteId() int32 {
	if x != nil {
		return x.ClienteId
	}
	return 0
}

func (x *CreateDriverRatingRequest) GetRepartidorId() int32 {
	if x != nil {
		return x.RepartidorId
	}
	return 0
}

func (x *CreateDriverRatingRequest) GetEstrellas() int32 {
	if x != nil {
		return x.Estrellas
	}
	return 0
}

func (x *CreateDriverRatingRequest) GetComentario() string {
	if x != nil {
		return x.Comentario
	}
	return ""
}

type CreateDriverRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RatingId      int32                  `protobuf:"varint,1,opt,name=rating_id,json=ratingId,proto3" json:"rating_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverRatingResponse) Reset() {
	*x = CreateDriverRatingResponse{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverRatingResponse) ProtoMessage() {}

func (x *CreateDriverRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverRatingResponse.ProtoReflect.Descriptor instead.
func (*CreateDriverRatingResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *CreateDriverRatingResponse) GetRatingId() int32 {
	if x != nil {
		return x.RatingId
	}
	return 0
}

func (x *CreateDriverRatingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetDriverRatingAverageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepartidorId  int32                  `protobuf:"varint,1,opt,name=repartidor_id,json=repartidorId,proto3" json:"repartidor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverRatingAverageRequest) Reset() {
	*x = GetDriverRatingAverageRequest{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverRatingAverageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverRatingAverageRequest) ProtoMessage() {}

func (x *GetDriverRatingAverageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverRatingAverageRequest.ProtoReflect.Descriptor instead.
func (*GetDriverRatingAverageRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetDriverRatingAverageRequest) GetRepartidorId() int32 {
	if x != nil {
		return x.RepartidorId
	}
	return 0
}

type GetDriverRatingAverageResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Promedio            float64                `protobuf:"fixed64,1,opt,name=promedio,proto3" json:"promedio,omitempty"`
	TotalCalificaciones int32                  `protobuf:"varint,2,opt,name=total_calificaciones,json=totalCalificaciones,proto3" json:"total_calificaciones,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetDriverRatingAverageResponse) Reset() {
	*x = GetDriverRatingAverageResponse{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverRatingAverageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverRatingAverageResponse) ProtoMessage() {}

func (x *GetDriverRatingAverageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverRatingAverageResponse.ProtoReflect.Descriptor instead.
func (*GetDriverRatingAverageResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetDriverRatingAverageResponse) GetPromedio() float64 {
	if x != nil {
		return x.Promedio
	}
	return 0
}

func (x *GetDriverRatingAverageResponse) GetTotalCalificaciones() int32 {
	if x != nil {
		return x.TotalCalificaciones
	}
	return 0
}

type CreateClientRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClienteId     int32                  `protobuf:"varint,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	RepartidorId  int32                  `protobuf:"varint,2,opt,name=repartidor_id,json=repartidorId,proto3" json:"repartidor_id,omitempty"`
	OrdenId       int32                  `protobuf:"varint,3,opt,name=orden_id,json=ordenId,proto3" json:"orden_id,omitempty"`
	Estrellas     int32                  `protobuf:"varint,4,opt,name=estrellas,proto3" json:"estrellas,omitempty"`
	Comentario    string                 `protobuf:"bytes,5,opt,name=comentario,proto3" json:"comentario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientRatingRequest) Reset() {
	*x = CreateClientRatingRequest{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRatingRequest) ProtoMessage() {}

func (x *CreateClientRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientRatingRequest.ProtoReflect.Descriptor instead.
func (*CreateClientRatingRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *CreateClientRatingRequest) GetClienteId() int32 {
	if x != nil {
		return x.ClienteId
	}
	return 0
}

func (x *CreateClientRatingRequest) GetRepartidorId() int32 {
	if x != nil {
		return x.RepartidorId
	}
	return 0
}

func (x *CreateClientRatingRequest) GetOrdenId() int32 {
	if x != nil {
		return x.OrdenId
	}
	return 0
}

func (x *CreateClientRatingRequest) GetEstrellas() int32 {
	if x != nil {
		return x.Estrellas
	}
	return 0
}

func (x *CreateClientRatingRequest) GetComentario() string {
	if x != nil {
		return x.Comentario
	}
	return ""
}

type CreateClientRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RatingId      int32                  `protobuf:"varint,1,opt,name=rating_id,json=ratingId,proto3" json:"rating_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClientRatingResponse) Reset() {
	*x = CreateClientRatingResponse{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClientRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClientRatingResponse) ProtoMessage() {}

func (x *CreateClientRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClientRatingResponse.ProtoReflect.Descriptor instead.
func (*CreateClientRatingResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *CreateClientRatingResponse) GetRatingId() int32 {
	if x != nil {
		return x.RatingId
	}
	return 0
}

func (x *CreateClientRatingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetClientRatingAverageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClienteId     int32                  `protobuf:"varint,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientRatingAverageRequest) Reset() {
	*x = GetClientRatingAverageRequest{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientRatingAverageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientRatingAverageRequest) ProtoMessage() {}

func (x *GetClientRatingAverageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientRatingAverageRequest.ProtoReflect.Descriptor instead.
func (*GetClientRatingAverageRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetClientRatingAverageRequest) GetClienteId() int32 {
	if x != nil {
		return x.ClienteId
	}
	return 0
}

type GetClientRatingAverageResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Promedio            float64                `protobuf:"fixed64,1,opt,name=promedio,proto3" json:"promedio,omitempty"`
	TotalCalificaciones int32                  `protobuf:"varint,2,opt,name=total_calificaciones,json=totalCalificaciones,proto3" json:"total_calificaciones,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetClientRatingAverageResponse) Reset() {
	*x = GetClientRatingAverageResponse{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientRatingAverageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientRatingAverageResponse) ProtoMessage() {}

func (x *GetClientRatingAverageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientRatingAverageResponse.ProtoReflect.Descriptor instead.
func (*GetClientRatingAverageResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *GetClientRatingAverageResponse) GetPromedio() float64 {
	if x != nil {
		return x.Promedio
	}
	return 0
}

func (x *GetClientRatingAverageResponse) GetTotalCalificaciones() int32 {
	if x != nil {
		return x.TotalCalificaciones
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x06userpb\"\x85\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12'\n" +
	"\x0fnombre_completo\x18\x04 \x01(\tR\x0enombreCompleto\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\"-\n" +
	"\x15GetUserByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"$\n" +
	"\x12GetUserByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"0\n" +
	"\fUserResponse\x12 \n" +
	"\x04user\x18\x01 \x01(\v2\f.userpb.UserR\x04user\"\x80\x01\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12'\n" +
	"\x0fnombre_completo\x18\x03 \x01(\tR\x0enombreCompleto\x12\x10\n" +
	"\x03rol\x18\x04 \x01(\tR\x03rol\"\x9c\x01\n" +
	"\x12CreateUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12'\n" +
	"\x0fnombre_completo\x18\x04 \x01(\tR\x0enombreCompleto\x12\x1a\n" +
	"\btelefono\x18\x05 \x01(\tR\btelefono\"d\n" +
	"\x10ListUsersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vrole_filter\x18\x03 \x01(\tR\n" +
	"roleFilter\"~\n" +
	"\x11ListUsersResponse\x12\"\n" +
	"\x05users\x18\x01 \x03(\v2\f.userpb.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x9d\x01\n" +
	"\x19CreateDriverRatingRequest\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x01 \x01(\x05R\tclienteId\x12#\n" +
	"\rrepartidor_id\x18\x02 \x01(\x05R\frepartidorId\x12\x1c\n" +
	"\testrellas\x18\x03 \x01(\x05R\testrellas\x12\x1e\n" +
	"\n" +
	"comentario\x18\x04 \x01(\tR\n" +
	"comentario\"S\n" +
	"\x1aCreateDriverRatingResponse\x12\x1b\n" +
	"\trating_id\x18\x01 \x01(\x05R\bratingId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\x1dGetDriverRatingAverageRequest\x12#\n" +
	"\rrepartidor_id\x18\x01 \x01(\x05R\frepartidorId\"o\n" +
	"\x1eGetDriverRatingAverageResponse\x12\x1a\n" +
	"\bpromedio\x18\x01 \x01(\x01R\bpromedio\x121\n" +
	"\x14total_calificaciones\x18\x02 \x01(\x05R\x13totalCalificaciones\"\xb8\x01\n" +
	"\x19CreateClientRatingRequest\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x01 \x01(\x05R\tclienteId\x12#\n" +
	"\rrepartidor_id\x18\x02 \x01(\x05R\frepartidorId\x12\x19\n" +
	"\borden_id\x18\x03 \x01(\x05R\aordenId\x12\x1c\n" +
	"\testrellas\x18\x04 \x01(\x05R\testrellas\x12\x1e\n" +
	"\n" +
	"comentario\x18\x05 \x01(\tR\n" +
	"comentario\"S\n" +
	"\x1aCreateClientRatingResponse\x12\x1b\n" +
	"\trating_id\x18\x01 \x01(\x05R\bratingId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\">\n" +
	"\x1dGetClientRatingAverageRequest\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x01 \x01(\x05R\tclienteId\"o\n" +
	"\x1eGetClientRatingAverageResponse\x12\x1a\n" +
	"\bpromedio\x18\x01 \x01(\x01R\bpromedio\x121\n" +
	"\x14total_calificaciones\x18\x02 \x01(\x05R\x13totalCalificaciones2\xa8\x05\n" +
	"\vUserService\x12E\n" +
	"\x0eGetUserByEmail\x12\x1d.userpb.GetUserByEmailRequest\x1a\x14.userpb.UserResponse\x12?\n" +
	"\vGetUserByID\x12\x1a.userpb.GetUserByIDRequest\x1a\x14.userpb.UserResponse\x12C\n" +
	"\n" +
	"CreateUser\x12\x19.userpb.CreateUserRequest\x1a\x1a.userpb.CreateUserResponse\x12@\n" +
	"\tListUsers\x12\x18.userpb.ListUsersRequest\x1a\x19.userpb.ListUsersResponse\x12[\n" +
	"\x12CreateDriverRating\x12!.userpb.CreateDriverRatingRequest\x1a\".userpb.CreateDriverRatingResponse\x12g\n" +
	"\x16GetDriverRatingAverage\x12%.userpb.GetDriverRatingAverageRequest\x1a&.userpb.GetDriverRatingAverageResponse\x12[\n" +
	"\x12CreateClientRating\x12!.userpb.CreateClientRatingRequest\x1a\".userpb.CreateClientRatingResponse\x12g\n" +
	"\x16GetClientRatingAverage\x12%.userpb.GetClientRatingAverageRequest\x1a&.userpb.GetClientRatingAverageResponseB\x17Z\x15delivery-proto/userpbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_user_proto_goTypes = []any{
	(*User)(nil),                           // 0: userpb.User
	(*GetUserByEmailRequest)(nil),          // 1: userpb.GetUserByEmailRequest
	(*GetUserByIDRequest)(nil),             // 2: userpb.GetUserByIDRequest
	(*UserResponse)(nil),                   // 3: userpb.UserResponse
	(*CreateUserRequest)(nil),              // 4: userpb.CreateUserRequest
	(*CreateUserResponse)(nil),             // 5: userpb.CreateUserResponse
	(*ListUsersRequest)(nil),               // 6: userpb.ListUsersRequest
	(*ListUsersResponse)(nil),              // 7: userpb.ListUsersResponse
	(*CreateDriverRatingRequest)(nil),      // 8: userpb.CreateDriverRatingRequest
	(*CreateDriverRatingResponse)(nil),     // 9: userpb.CreateDriverRatingResponse
	(*GetDriverRatingAverageRequest)(nil),  // 10: userpb.GetDriverRatingAverageRequest
	(*GetDriverRatingAverageResponse)(nil), // 11: userpb.GetDriverRatingAverageResponse
	(*CreateClientRatingRequest)(nil),      // 12: userpb.CreateClientRatingRequest
	(*CreateClientRatingResponse)(nil),     // 13: userpb.CreateClientRatingResponse
	(*GetClientRatingAverageRequest)(nil),  // 14: userpb.GetClientRatingAverageRequest
	(*GetClientRatingAverageResponse)(nil), // 15: userpb.GetClientRatingAverageResponse
}
var file_user_proto_depIdxs = []int32{
	0,  // 0: userpb.UserResponse.user:type_name -> userpb.User
	0,  // 1: userpb.ListUsersResponse.users:type_name -> userpb.User
	1,  // 2: userpb.UserService.GetUserByEmail:input_type -> userpb.GetUserByEmailRequest
	2,  // 3: userpb.UserService.GetUserByID:input_type -> userpb.GetUserByIDRequest
	4,  // 4: userpb.UserService.CreateUser:input_type -> userpb.CreateUserRequest
	6,  // 5: userpb.UserService.ListUsers:input_type -> userpb.ListUsersRequest
	8,  // 6: userpb.UserService.CreateDriverRating:input_type -> userpb.CreateDriverRatingRequest
	10, // 7: userpb.UserService.GetDriverRatingAverage:input_type -> userpb.GetDriverRatingAverageRequest
	12, // 8: userpb.UserService.CreateClientRating:input_type -> userpb.CreateClientRatingRequest
	14, // 9: userpb.UserService.GetClientRatingAverage:input_type -> userpb.GetClientRatingAverageRequest
	3,  // 10: userpb.UserService.GetUserByEmail:output_type -> userpb.UserResponse
	3,  // 11: userpb.UserService.GetUserByID:output_type -> userpb.UserResponse
	5,  // 12: userpb.UserService.CreateUser:output_type -> userpb.CreateUserResponse
	7,  // 13: userpb.UserService.ListUsers:output_type -> userpb.ListUsersResponse
	9,  // 14: userpb.UserService.CreateDriverRating:output_type -> userpb.CreateDriverRatingResponse
	11, // 15: userpb.UserService.GetDriverRatingAverage:output_type -> userpb.GetDriverRatingAverageResponse
	13, // 16: userpb.UserService.CreateClientRating:output_type -> userpb.CreateClientRatingResponse
	15, // 17: userpb.UserService.GetClientRatingAverage:output_type -> userpb.GetClientRatingAverageResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
