apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: deliver-eats-prod-frontendconfig
  namespace: deliver-eats
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
