// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: catalogpb/catalog.proto

package catalogpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int32                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogRequest) Reset() {
	*x = GetCatalogRequest{}
	mi := &file_catalogpb_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogRequest) ProtoMessage() {}

func (x *GetCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogpb_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogRequest.ProtoReflect.Descriptor instead.
func (*GetCatalogRequest) Descriptor() ([]byte, []int) {
	return file_catalogpb_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *GetCatalogRequest) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RestaurantId  int32                  `protobuf:"varint,2,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Nombre        string                 `protobuf:"bytes,3,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Descripcion   string                 `protobuf:"bytes,4,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	Precio        float64                `protobuf:"fixed64,5,opt,name=precio,proto3" json:"precio,omitempty"`
	Disponible    bool                   `protobuf:"varint,6,opt,name=disponible,proto3" json:"disponible,omitempty"`
	Categoria     string                 `protobuf:"bytes,7,opt,name=categoria,proto3" json:"categoria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_catalogpb_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_catalogpb_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_catalogpb_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Product) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *Product) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Product) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *Product) GetPrecio() float64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *Product) GetDisponible() bool {
	if x != nil {
		return x.Disponible
	}
	return false
}

func (x *Product) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

type GetCatalogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogResponse) Reset() {
	*x = GetCatalogResponse{}
	mi := &file_catalogpb_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogResponse) ProtoMessage() {}

func (x *GetCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalogpb_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogResponse.ProtoReflect.Descriptor instead.
func (*GetCatalogResponse) Descriptor() ([]byte, []int) {
	return file_catalogpb_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *GetCatalogResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type GetProductsByRestaurantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestauranteId int32                  `protobuf:"varint,1,opt,name=restaurante_id,json=restauranteId,proto3" json:"restaurante_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByRestaurantRequest) Reset() {
	*x = GetProductsByRestaurantRequest{}
	mi := &file_catalogpb_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByRestaurantRequest) ProtoMessage() {}

func (x *GetProductsByRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogpb_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByRestaurantRequest.ProtoReflect.Descriptor instead.
func (*GetProductsByRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_catalogpb_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductsByRestaurantRequest) GetRestauranteId() int32 {
	if x != nil {
		return x.RestauranteId
	}
	return 0
}

type GetProductsByRestaurantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByRestaurantResponse) Reset() {
	*x = GetProductsByRestaurantResponse{}
	mi := &file_catalogpb_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByRestaurantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByRestaurantResponse) ProtoMessage() {}

func (x *GetProductsByRestaurantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalogpb_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByRestaurantResponse.ProtoReflect.Descriptor instead.
func (*GetProductsByRestaurantResponse) Descriptor() ([]byte, []int) {
	return file_catalogpb_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductsByRestaurantResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type GetProductsByIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int32                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByIDsRequest) Reset() {
	*x = GetProductsByIDsRequest{}
	mi := &file_catalogpb_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByIDsRequest) ProtoMessage() {}

func (x *GetProductsByIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogpb_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByIDsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsByIDsRequest) Descriptor() ([]byte, []int) {
	return file_catalogpb_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductsByIDsRequest) GetIds() []int32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetProductsByIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByIDsResponse) Reset() {
	*x = GetProductsByIDsResponse{}
	mi := &file_catalogpb_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByIDsResponse) ProtoMessage() {}

func (x *GetProductsByIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalogpb_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByIDsResponse.ProtoReflect.Descriptor instead.
func (*GetProductsByIDsResponse) Descriptor() ([]byte, []int) {
	return file_catalogpb_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *GetProductsByIDsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_catalogpb_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogpb_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_catalogpb_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *GetProductRequest) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Precio        float64                `protobuf:"fixed64,3,opt,name=precio,proto3" json:"precio,omitempty"`
	Disponible    bool                   `protobuf:"varint,4,opt,name=disponible,proto3" json:"disponible,omitempty"`
	RestauranteId int32                  `protobuf:"varint,5,opt,name=restaurante_id,json=restauranteId,proto3" json:"restaurante_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_catalogpb_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalogpb_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_catalogpb_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *GetProductResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetProductResponse) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *GetProductResponse) GetPrecio() float64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *GetProductResponse) GetDisponible() bool {
	if x != nil {
		return x.Disponible
	}
	return false
}

func (x *GetProductResponse) GetRestauranteId() int32 {
	if x != nil {
		return x.RestauranteId
	}
	return 0
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nombre        string                 `protobuf:"bytes,1,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Descripcion   string                 `protobuf:"bytes,2,opt,name=descripcion,proto3" json:"descripcion,omitempty"`
	RestauranteId int32                  `protobuf:"varint,3,opt,name=restaurante_id,json=restauranteId,proto3" json:"restaurante_id,omitempty"`
	Precio        float64                `protobuf:"fixed64,4,opt,name=precio,proto3" json:"precio,omitempty"`
	Categoria     string                 `protobuf:"bytes,5,opt,name=categoria,proto3" json:"categoria,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_catalogpb_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalogpb_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_catalogpb_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *CreateProductRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *CreateProductRequest) GetDescripcion() string {
	if x != nil {
		return x.Descripcion
	}
	return ""
}

func (x *CreateProductRequest) GetRestauranteId() int32 {
	if x != nil {
		return x.RestauranteId
	}
	return 0
}

func (x *CreateProductRequest) GetPrecio() float64 {
	if x != nil {
		return x.Precio
	}
	return 0
}

func (x *CreateProductRequest) GetCategoria() string {
	if x != nil {
		return x.Categoria
	}
	return ""
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     int32                  `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_catalogpb_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalogpb_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_catalogpb_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *CreateProductResponse) GetProductId() int32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateProductResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_catalogpb_catalog_proto protoreflect.FileDescriptor

const file_catalogpb_catalog_proto_rawDesc = "" +
	"\n" +
	"\x17catalogpb/catalog.proto\x12\acatalog\"8\n" +
	"\x11GetCatalogRequest\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x05R\frestaurantId\"\xce\x01\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12#\n" +
	"\rrestaurant_id\x18\x02 \x01(\x05R\frestaurantId\x12\x16\n" +
	"\x06nombre\x18\x03 \x01(\tR\x06nombre\x12 \n" +
	"\vdescripcion\x18\x04 \x01(\tR\vdescripcion\x12\x16\n" +
	"\x06precio\x18\x05 \x01(\x01R\x06precio\x12\x1e\n" +
	"\n" +
	"disponible\x18\x06 \x01(\bR\n" +
	"disponible\x12\x1c\n" +
	"\tcategoria\x18\a \x01(\tR\tcategoria\"B\n" +
	"\x12GetCatalogResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.catalog.ProductR\bproducts\"G\n" +
	"\x1eGetProductsByRestaurantRequest\x12%\n" +
	"\x0erestaurante_id\x18\x01 \x01(\x05R\rrestauranteId\"O\n" +
	"\x1fGetProductsByRestaurantResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.catalog.ProductR\bproducts\"+\n" +
	"\x17GetProductsByIDsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x05R\x03ids\"H\n" +
	"\x18GetProductsByIDsResponse\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.catalog.ProductR\bproducts\"2\n" +
	"\x11GetProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\"\x9b\x01\n" +
	"\x12GetProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x16\n" +
	"\x06precio\x18\x03 \x01(\x01R\x06precio\x12\x1e\n" +
	"\n" +
	"disponible\x18\x04 \x01(\bR\n" +
	"disponible\x12%\n" +
	"\x0erestaurante_id\x18\x05 \x01(\x05R\rrestauranteId\"\xad\x01\n" +
	"\x14CreateProductRequest\x12\x16\n" +
	"\x06nombre\x18\x01 \x01(\tR\x06nombre\x12 \n" +
	"\vdescripcion\x18\x02 \x01(\tR\vdescripcion\x12%\n" +
	"\x0erestaurante_id\x18\x03 \x01(\x05R\rrestauranteId\x12\x16\n" +
	"\x06precio\x18\x04 \x01(\x01R\x06precio\x12\x1c\n" +
	"\tcategoria\x18\x05 \x01(\tR\tcategoria\"P\n" +
	"\x15CreateProductResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x05R\tproductId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xee\x02\n" +
	"\x0eCatalogService\x12l\n" +
	"\x17GetProductsByRestaurant\x12'.catalog.GetProductsByRestaurantRequest\x1a(.catalog.GetProductsByRestaurantResponse\x12W\n" +
	"\x10GetProductsByIDs\x12 .catalog.GetProductsByIDsRequest\x1a!.catalog.GetProductsByIDsResponse\x12E\n" +
	"\n" +
	"GetProduct\x12\x1a.catalog.GetProductRequest\x1a\x1b.catalog.GetProductResponse\x12N\n" +
	"\rCreateProduct\x12\x1d.catalog.CreateProductRequest\x1a\x1e.catalog.CreateProductResponseB\x1aZ\x18delivery-proto/catalogpbb\x06proto3"

var (
	file_catalogpb_catalog_proto_rawDescOnce sync.Once
	file_catalogpb_catalog_proto_rawDescData []byte
)

func file_catalogpb_catalog_proto_rawDescGZIP() []byte {
	file_catalogpb_catalog_proto_rawDescOnce.Do(func() {
		file_catalogpb_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalogpb_catalog_proto_rawDesc), len(file_catalogpb_catalog_proto_rawDesc)))
	})
	return file_catalogpb_catalog_proto_rawDescData
}

var file_catalogpb_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_catalogpb_catalog_proto_goTypes = []any{
	(*GetCatalogRequest)(nil),               // 0: catalog.GetCatalogRequest
	(*Product)(nil),                         // 1: catalog.Product
	(*GetCatalogResponse)(nil),              // 2: catalog.GetCatalogResponse
	(*GetProductsByRestaurantRequest)(nil),  // 3: catalog.GetProductsByRestaurantRequest
	(*GetProductsByRestaurantResponse)(nil), // 4: catalog.GetProductsByRestaurantResponse
	(*GetProductsByIDsRequest)(nil),         // 5: catalog.GetProductsByIDsRequest
	(*GetProductsByIDsResponse)(nil),        // 6: catalog.GetProductsByIDsResponse
	(*GetProductRequest)(nil),               // 7: catalog.GetProductRequest
	(*GetProductResponse)(nil),              // 8: catalog.GetProductResponse
	(*CreateProductRequest)(nil),            // 9: catalog.CreateProductRequest
	(*CreateProductResponse)(nil),           // 10: catalog.CreateProductResponse
}
var file_catalogpb_catalog_proto_depIdxs = []int32{
	1,  // 0: catalog.GetCatalogResponse.products:type_name -> catalog.Product
	1,  // 1: catalog.GetProductsByRestaurantResponse.products:type_name -> catalog.Product
	1,  // 2: catalog.GetProductsByIDsResponse.products:type_name -> catalog.Product
	3,  // 3: catalog.CatalogService.GetProductsByRestaurant:input_type -> catalog.GetProductsByRestaurantRequest
	5,  // 4: catalog.CatalogService.GetProductsByIDs:input_type -> catalog.GetProductsByIDsRequest
	7,  // 5: catalog.CatalogService.GetProduct:input_type -> catalog.GetProductRequest
	9,  // 6: catalog.CatalogService.CreateProduct:input_type -> catalog.CreateProductRequest
	4,  // 7: catalog.CatalogService.GetProductsByRestaurant:output_type -> catalog.GetProductsByRestaurantResponse
	6,  // 8: catalog.CatalogService.GetProductsByIDs:output_type -> catalog.GetProductsByIDsResponse
	8,  // 9: catalog.CatalogService.GetProduct:output_type -> catalog.GetProductResponse
	10, // 10: catalog.CatalogService.CreateProduct:output_type -> catalog.CreateProductResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_catalogpb_catalog_proto_init() }
func file_catalogpb_catalog_proto_init() {
	if File_catalogpb_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalogpb_catalog_proto_rawDesc), len(file_catalogpb_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalogpb_catalog_proto_goTypes,
		DependencyIndexes: file_catalogpb_catalog_proto_depIdxs,
		MessageInfos:      file_catalogpb_catalog_proto_msgTypes,
	}.Build()
	File_catalogpb_catalog_proto = out.File
	file_catalogpb_catalog_proto_goTypes = nil
	file_catalogpb_catalog_proto_depIdxs = nil
}
