// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: notificationpb/notification.proto

package notificationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendOrderCanceledEmailRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Email            string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	OrderId          int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Productos        string                 `protobuf:"bytes,3,opt,name=productos,proto3" json:"productos,omitempty"`
	FechaCancelacion string                 `protobuf:"bytes,4,opt,name=fecha_cancelacion,json=fechaCancelacion,proto3" json:"fecha_cancelacion,omitempty"`
	NombreUsuario    string                 `protobuf:"bytes,5,opt,name=nombre_usuario,json=nombreUsuario,proto3" json:"nombre_usuario,omitempty"`
	RolUsuario       string                 `protobuf:"bytes,6,opt,name=rol_usuario,json=rolUsuario,proto3" json:"rol_usuario,omitempty"`
	Motivo           string                 `protobuf:"bytes,7,opt,name=motivo,proto3" json:"motivo,omitempty"`
	Estado           string                 `protobuf:"bytes,8,opt,name=estado,proto3" json:"estado,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SendOrderCanceledEmailRequest) Reset() {
	*x = SendOrderCanceledEmailRequest{}
	mi := &file_notificationpb_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOrderCanceledEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOrderCanceledEmailRequest) ProtoMessage() {}

func (x *SendOrderCanceledEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notificationpb_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOrderCanceledEmailRequest.ProtoReflect.Descriptor instead.
func (*SendOrderCanceledEmailRequest) Descriptor() ([]byte, []int) {
	return file_notificationpb_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SendOrderCanceledEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SendOrderCanceledEmailRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *SendOrderCanceledEmailRequest) GetProductos() string {
	if x != nil {
		return x.Productos
	}
	return ""
}

func (x *SendOrderCanceledEmailRequest) GetFechaCancelacion() string {
	if x != nil {
		return x.FechaCancelacion
	}
	return ""
}

func (x *SendOrderCanceledEmailRequest) GetNombreUsuario() string {
	if x != nil {
		return x.NombreUsuario
	}
	return ""
}

func (x *SendOrderCanceledEmailRequest) GetRolUsuario() string {
	if x != nil {
		return x.RolUsuario
	}
	return ""
}

func (x *SendOrderCanceledEmailRequest) GetMotivo() string {
	if x != nil {
		return x.Motivo
	}
	return ""
}

func (x *SendOrderCanceledEmailRequest) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

type SendOrderCanceledEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOrderCanceledEmailResponse) Reset() {
	*x = SendOrderCanceledEmailResponse{}
	mi := &file_notificationpb_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOrderCanceledEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOrderCanceledEmailResponse) ProtoMessage() {}

func (x *SendOrderCanceledEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notificationpb_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOrderCanceledEmailResponse.ProtoReflect.Descriptor instead.
func (*SendOrderCanceledEmailResponse) Descriptor() ([]byte, []int) {
	return file_notificationpb_notification_proto_rawDescGZIP(), []int{1}
}

func (x *SendOrderCanceledEmailResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_notificationpb_notification_proto protoreflect.FileDescriptor

const file_notificationpb_notification_proto_rawDesc = "" +
	"\n" +
	"!notificationpb/notification.proto\x12\fnotification\"\x93\x02\n" +
	"\x1dSendOrderCanceledEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12\x1c\n" +
	"\tproductos\x18\x03 \x01(\tR\tproductos\x12+\n" +
	"\x11fecha_cancelacion\x18\x04 \x01(\tR\x10fechaCancelacion\x12%\n" +
	"\x0enombre_usuario\x18\x05 \x01(\tR\rnombreUsuario\x12\x1f\n" +
	"\vrol_usuario\x18\x06 \x01(\tR\n" +
	"rolUsuario\x12\x16\n" +
	"\x06motivo\x18\a \x01(\tR\x06motivo\x12\x16\n" +
	"\x06estado\x18\b \x01(\tR\x06estado\":\n" +
	"\x1eSendOrderCanceledEmailResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x8a\x01\n" +
	"\x13NotificationService\x12s\n" +
	"\x16SendOrderCanceledEmail\x12+.notification.SendOrderCanceledEmailRequest\x1a,.notification.SendOrderCanceledEmailResponseB\x1fZ\x1ddelivery-proto/notificationpbb\x06proto3"

var (
	file_notificationpb_notification_proto_rawDescOnce sync.Once
	file_notificationpb_notification_proto_rawDescData []byte
)

func file_notificationpb_notification_proto_rawDescGZIP() []byte {
	file_notificationpb_notification_proto_rawDescOnce.Do(func() {
		file_notificationpb_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notificationpb_notification_proto_rawDesc), len(file_notificationpb_notification_proto_rawDesc)))
	})
	return file_notificationpb_notification_proto_rawDescData
}

var file_notificationpb_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notificationpb_notification_proto_goTypes = []any{
	(*SendOrderCanceledEmailRequest)(nil),  // 0: notification.SendOrderCanceledEmailRequest
	(*SendOrderCanceledEmailResponse)(nil), // 1: notification.SendOrderCanceledEmailResponse
}
var file_notificationpb_notification_proto_depIdxs = []int32{
	0, // 0: notification.NotificationService.SendOrderCanceledEmail:input_type -> notification.SendOrderCanceledEmailRequest
	1, // 1: notification.NotificationService.SendOrderCanceledEmail:output_type -> notification.SendOrderCanceledEmailResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notificationpb_notification_proto_init() }
func file_notificationpb_notification_proto_init() {
	if File_notificationpb_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notificationpb_notification_proto_rawDesc), len(file_notificationpb_notification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notificationpb_notification_proto_goTypes,
		DependencyIndexes: file_notificationpb_notification_proto_depIdxs,
		MessageInfos:      file_notificationpb_notification_proto_msgTypes,
	}.Build()
	File_notificationpb_notification_proto = out.File
	file_notificationpb_notification_proto_goTypes = nil
	file_notificationpb_notification_proto_depIdxs = nil
}
