// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: paymentpb/payment.proto

package paymentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	UseCupon      bool                   `protobuf:"varint,3,opt,name=use_cupon,json=useCupon,proto3" json:"use_cupon,omitempty"`
	ClientId      int32                  `protobuf:"varint,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_paymentpb_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paymentpb_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_paymentpb_payment_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessPaymentRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ProcessPaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *ProcessPaymentRequest) GetUseCupon() bool {
	if x != nil {
		return x.UseCupon
	}
	return false
}

func (x *ProcessPaymentRequest) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type ProcessPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     int32                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_paymentpb_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paymentpb_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_paymentpb_payment_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessPaymentResponse) GetPaymentId() int32 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *ProcessPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessPaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RefundPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentRequest) Reset() {
	*x = RefundPaymentRequest{}
	mi := &file_paymentpb_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentRequest) ProtoMessage() {}

func (x *RefundPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paymentpb_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentRequest.ProtoReflect.Descriptor instead.
func (*RefundPaymentRequest) Descriptor() ([]byte, []int) {
	return file_paymentpb_payment_proto_rawDescGZIP(), []int{2}
}

func (x *RefundPaymentRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type RefundPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundPaymentResponse) Reset() {
	*x = RefundPaymentResponse{}
	mi := &file_paymentpb_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundPaymentResponse) ProtoMessage() {}

func (x *RefundPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paymentpb_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundPaymentResponse.ProtoReflect.Descriptor instead.
func (*RefundPaymentResponse) Descriptor() ([]byte, []int) {
	return file_paymentpb_payment_proto_rawDescGZIP(), []int{3}
}

func (x *RefundPaymentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefundPaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      int32                  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // opcional (para filtrar pagos de un cliente)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentsRequest) Reset() {
	*x = GetPaymentsRequest{}
	mi := &file_paymentpb_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentsRequest) ProtoMessage() {}

func (x *GetPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paymentpb_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentsRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_paymentpb_payment_proto_rawDescGZIP(), []int{4}
}

func (x *GetPaymentsRequest) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       int32                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ClientId      int32                  `protobuf:"varint,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	PrecioFinal   float64                `protobuf:"fixed64,4,opt,name=precio_final,json=precioFinal,proto3" json:"precio_final,omitempty"`
	Estado        string                 `protobuf:"bytes,5,opt,name=estado,proto3" json:"estado,omitempty"`
	UsaCupon      bool                   `protobuf:"varint,6,opt,name=usa_cupon,json=usaCupon,proto3" json:"usa_cupon,omitempty"`
	MetodoPago    string                 `protobuf:"bytes,7,opt,name=metodo_pago,json=metodoPago,proto3" json:"metodo_pago,omitempty"`
	Moneda        string                 `protobuf:"bytes,8,opt,name=moneda,proto3" json:"moneda,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_paymentpb_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_paymentpb_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_paymentpb_payment_proto_rawDescGZIP(), []int{5}
}

func (x *Payment) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payment) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Payment) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Payment) GetPrecioFinal() float64 {
	if x != nil {
		return x.PrecioFinal
	}
	return 0
}

func (x *Payment) GetEstado() string {
	if x != nil {
		return x.Estado
	}
	return ""
}

func (x *Payment) GetUsaCupon() bool {
	if x != nil {
		return x.UsaCupon
	}
	return false
}

func (x *Payment) GetMetodoPago() string {
	if x != nil {
		return x.MetodoPago
	}
	return ""
}

func (x *Payment) GetMoneda() string {
	if x != nil {
		return x.Moneda
	}
	return ""
}

type GetPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentsResponse) Reset() {
	*x = GetPaymentsResponse{}
	mi := &file_paymentpb_payment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentsResponse) ProtoMessage() {}

func (x *GetPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paymentpb_payment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentsResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_paymentpb_payment_proto_rawDescGZIP(), []int{6}
}

func (x *GetPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

var File_paymentpb_payment_proto protoreflect.FileDescriptor

const file_paymentpb_payment_proto_rawDesc = "" +
	"\n" +
	"\x17paymentpb/payment.proto\x12\apayment\"\x93\x01\n" +
	"\x15ProcessPaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\tR\rpaymentMethod\x12\x1b\n" +
	"\tuse_cupon\x18\x03 \x01(\bR\buseCupon\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\x05R\bclientId\"i\n" +
	"\x16ProcessPaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x05R\tpaymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"1\n" +
	"\x14RefundPaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\"K\n" +
	"\x15RefundPaymentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"1\n" +
	"\x12GetPaymentsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\x05R\bclientId\"\xe2\x01\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x05R\aorderId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\x05R\bclientId\x12!\n" +
	"\fprecio_final\x18\x04 \x01(\x01R\vprecioFinal\x12\x16\n" +
	"\x06estado\x18\x05 \x01(\tR\x06estado\x12\x1b\n" +
	"\tusa_cupon\x18\x06 \x01(\bR\busaCupon\x12\x1f\n" +
	"\vmetodo_pago\x18\a \x01(\tR\n" +
	"metodoPago\x12\x16\n" +
	"\x06moneda\x18\b \x01(\tR\x06moneda\"C\n" +
	"\x13GetPaymentsResponse\x12,\n" +
	"\bpayments\x18\x01 \x03(\v2\x10.payment.PaymentR\bpayments2\xfd\x01\n" +
	"\x0ePaymentService\x12Q\n" +
	"\x0eProcessPayment\x12\x1e.payment.ProcessPaymentRequest\x1a\x1f.payment.ProcessPaymentResponse\x12N\n" +
	"\rRefundPayment\x12\x1d.payment.RefundPaymentRequest\x1a\x1e.payment.RefundPaymentResponse\x12H\n" +
	"\vGetPayments\x12\x1b.payment.GetPaymentsRequest\x1a\x1c.payment.GetPaymentsResponseB\x1aZ\x18delivery-proto/paymentpbb\x06proto3"

var (
	file_paymentpb_payment_proto_rawDescOnce sync.Once
	file_paymentpb_payment_proto_rawDescData []byte
)

func file_paymentpb_payment_proto_rawDescGZIP() []byte {
	file_paymentpb_payment_proto_rawDescOnce.Do(func() {
		file_paymentpb_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paymentpb_payment_proto_rawDesc), len(file_paymentpb_payment_proto_rawDesc)))
	})
	return file_paymentpb_payment_proto_rawDescData
}

var file_paymentpb_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_paymentpb_payment_proto_goTypes = []any{
	(*ProcessPaymentRequest)(nil),  // 0: payment.ProcessPaymentRequest
	(*ProcessPaymentResponse)(nil), // 1: payment.ProcessPaymentResponse
	(*RefundPaymentRequest)(nil),   // 2: payment.RefundPaymentRequest
	(*RefundPaymentResponse)(nil),  // 3: payment.RefundPaymentResponse
	(*GetPaymentsRequest)(nil),     // 4: payment.GetPaymentsRequest
	(*Payment)(nil),                // 5: payment.Payment
	(*GetPaymentsResponse)(nil),    // 6: payment.GetPaymentsResponse
}
var file_paymentpb_payment_proto_depIdxs = []int32{
	5, // 0: payment.GetPaymentsResponse.payments:type_name -> payment.Payment
	0, // 1: payment.PaymentService.ProcessPayment:input_type -> payment.ProcessPaymentRequest
	2, // 2: payment.PaymentService.RefundPayment:input_type -> payment.RefundPaymentRequest
	4, // 3: payment.PaymentService.GetPayments:input_type -> payment.GetPaymentsRequest
	1, // 4: payment.PaymentService.ProcessPayment:output_type -> payment.ProcessPaymentResponse
	3, // 5: payment.PaymentService.RefundPayment:output_type -> payment.RefundPaymentResponse
	6, // 6: payment.PaymentService.GetPayments:output_type -> payment.GetPaymentsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_paymentpb_payment_proto_init() }
func file_paymentpb_payment_proto_init() {
	if File_paymentpb_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paymentpb_payment_proto_rawDesc), len(file_paymentpb_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paymentpb_payment_proto_goTypes,
		DependencyIndexes: file_paymentpb_payment_proto_depIdxs,
		MessageInfos:      file_paymentpb_payment_proto_msgTypes,
	}.Build()
	File_paymentpb_payment_proto = out.File
	file_paymentpb_payment_proto_goTypes = nil
	file_paymentpb_payment_proto_depIdxs = nil
}
