// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: paymentpb/payment.proto

package paymentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	UseCupon      bool                   `protobuf:"varint,3,opt,name=use_cupon,json=useCupon,proto3" json:"use_cupon,omitempty"`
	ClientId      int32                  `protobuf:"varint,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentRequest) Reset() {
	*x = ProcessPaymentRequest{}
	mi := &file_paymentpb_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRequest) ProtoMessage() {}

func (x *ProcessPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paymentpb_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRequest.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRequest) Descriptor() ([]byte, []int) {
	return file_paymentpb_payment_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessPaymentRequest) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ProcessPaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *ProcessPaymentRequest) GetUseCupon() bool {
	if x != nil {
		return x.UseCupon
	}
	return false
}

func (x *ProcessPaymentRequest) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type ProcessPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     int32                  `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPaymentResponse) Reset() {
	*x = ProcessPaymentResponse{}
	mi := &file_paymentpb_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResponse) ProtoMessage() {}

func (x *ProcessPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paymentpb_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResponse.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResponse) Descriptor() ([]byte, []int) {
	return file_paymentpb_payment_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessPaymentResponse) GetPaymentId() int32 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *ProcessPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProcessPaymentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_paymentpb_payment_proto protoreflect.FileDescriptor

const file_paymentpb_payment_proto_rawDesc = "" +
	"\n" +
	"\x17paymentpb/payment.proto\x12\apayment\"\x93\x01\n" +
	"\x15ProcessPaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\tR\rpaymentMethod\x12\x1b\n" +
	"\tuse_cupon\x18\x03 \x01(\bR\buseCupon\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\x05R\bclientId\"i\n" +
	"\x16ProcessPaymentResponse\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\x05R\tpaymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2c\n" +
	"\x0ePaymentService\x12Q\n" +
	"\x0eProcessPayment\x12\x1e.payment.ProcessPaymentRequest\x1a\x1f.payment.ProcessPaymentResponseB\x1aZ\x18delivery-proto/paymentpbb\x06proto3"

var (
	file_paymentpb_payment_proto_rawDescOnce sync.Once
	file_paymentpb_payment_proto_rawDescData []byte
)

func file_paymentpb_payment_proto_rawDescGZIP() []byte {
	file_paymentpb_payment_proto_rawDescOnce.Do(func() {
		file_paymentpb_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paymentpb_payment_proto_rawDesc), len(file_paymentpb_payment_proto_rawDesc)))
	})
	return file_paymentpb_payment_proto_rawDescData
}

var file_paymentpb_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_paymentpb_payment_proto_goTypes = []any{
	(*ProcessPaymentRequest)(nil),  // 0: payment.ProcessPaymentRequest
	(*ProcessPaymentResponse)(nil), // 1: payment.ProcessPaymentResponse
}
var file_paymentpb_payment_proto_depIdxs = []int32{
	0, // 0: payment.PaymentService.ProcessPayment:input_type -> payment.ProcessPaymentRequest
	1, // 1: payment.PaymentService.ProcessPayment:output_type -> payment.ProcessPaymentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_paymentpb_payment_proto_init() }
func file_paymentpb_payment_proto_init() {
	if File_paymentpb_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paymentpb_payment_proto_rawDesc), len(file_paymentpb_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paymentpb_payment_proto_goTypes,
		DependencyIndexes: file_paymentpb_payment_proto_depIdxs,
		MessageInfos:      file_paymentpb_payment_proto_msgTypes,
	}.Build()
	File_paymentpb_payment_proto = out.File
	file_paymentpb_payment_proto_goTypes = nil
	file_paymentpb_payment_proto_depIdxs = nil
}
