// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
package convertpb

import (
	context "context"
	grpc "google.golang.org/grpc"
)

type ConvertServiceClient interface {
	GetExchangeRate(ctx context.Context, in *ExchangeRateRequest, opts ...grpc.CallOption) (*ExchangeRateResponse, error)
	ConvertCurrency(ctx context.Context, in *ConversionRequest, opts ...grpc.CallOption) (*ConversionResponse, error)
}

type ConvertServiceServer interface {
	GetExchangeRate(context.Context, *ExchangeRateRequest) (*ExchangeRateResponse, error)
	ConvertCurrency(context.Context, *ConversionRequest) (*ConversionResponse, error)
}

type UnimplementedConvertServiceServer struct{}

func (UnimplementedConvertServiceServer) GetExchangeRate(context.Context, *ExchangeRateRequest) (*ExchangeRateResponse, error) {
	return nil, nil
}

func (UnimplementedConvertServiceServer) ConvertCurrency(context.Context, *ConversionRequest) (*ConversionResponse, error) {
	return nil, nil
}
