// Code generated by protoc-gen-go. DO NOT EDIT.
package convertpb

type ExchangeRateRequest struct {
	From string
	To   string
}

type ExchangeRateResponse struct {
	FromCurrency string
	ToCurrency   string
	Rate         float64
	Timestamp    int64
	Source       string
}

type ConversionRequest struct {
	FromCurrency string
	ToCurrency   string
	Amount       float64
}

type ConversionResponse struct {
	FromCurrency string
	ToCurrency   string
	AmountFrom   float64
	AmountTo     float64
	Rate         float64
	Timestamp    int64
	Source       string
}
