apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: deliver-eats
  labels:
    app.kubernetes.io/part-of: deliver-eats
type: Opaque
stringData:
  DB_HOST: "sa-delivereats.database.windows.net"
  DB_USER: "adminsql"
  DB_PASSWORD: "Delivereats123"

  JWT_SECRET: "static_vibrations_luis_is_gay"
  JWT_EXPIRATION_HOURS: "4"

  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: "dfacundoperezn@gmail.com"
  SMTP_PASS: "vqdguhggssmanfvu"
  SMTP_FROM: "dfacundoperezn@gmail.com"

  EXCHANGE_API_KEY: "d2f0e9b374a9a45ab38bbc24"
  REDIS_PASSWORD: ""

  RABBITMQ_USER: "delivery"
  RABBITMQ_PASSWORD: "delivery123"
  RABBITMQ_URL: "amqp://delivery:delivery123@rabbitmq:5672/"
