// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: restaurantpb/restaurant.proto

package restaurantpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_restaurantpb_restaurant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantpb_restaurant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_restaurantpb_restaurant_proto_rawDescGZIP(), []int{0}
}

type Restaurant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Direccion     string                 `protobuf:"bytes,3,opt,name=direccion,proto3" json:"direccion,omitempty"`
	Latitud       float64                `protobuf:"fixed64,4,opt,name=latitud,proto3" json:"latitud,omitempty"`
	Longitud      float64                `protobuf:"fixed64,5,opt,name=longitud,proto3" json:"longitud,omitempty"`
	Telefono      string                 `protobuf:"bytes,6,opt,name=telefono,proto3" json:"telefono,omitempty"`
	Calificacion  float64                `protobuf:"fixed64,7,opt,name=calificacion,proto3" json:"calificacion,omitempty"`
	Activo        bool                   `protobuf:"varint,8,opt,name=activo,proto3" json:"activo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restaurant) Reset() {
	*x = Restaurant{}
	mi := &file_restaurantpb_restaurant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restaurant) ProtoMessage() {}

func (x *Restaurant) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantpb_restaurant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restaurant.ProtoReflect.Descriptor instead.
func (*Restaurant) Descriptor() ([]byte, []int) {
	return file_restaurantpb_restaurant_proto_rawDescGZIP(), []int{1}
}

func (x *Restaurant) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Restaurant) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *Restaurant) GetDireccion() string {
	if x != nil {
		return x.Direccion
	}
	return ""
}

func (x *Restaurant) GetLatitud() float64 {
	if x != nil {
		return x.Latitud
	}
	return 0
}

func (x *Restaurant) GetLongitud() float64 {
	if x != nil {
		return x.Longitud
	}
	return 0
}

func (x *Restaurant) GetTelefono() string {
	if x != nil {
		return x.Telefono
	}
	return ""
}

func (x *Restaurant) GetCalificacion() float64 {
	if x != nil {
		return x.Calificacion
	}
	return 0
}

func (x *Restaurant) GetActivo() bool {
	if x != nil {
		return x.Activo
	}
	return false
}

type RestaurantListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurants   []*Restaurant          `protobuf:"bytes,1,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantListResponse) Reset() {
	*x = RestaurantListResponse{}
	mi := &file_restaurantpb_restaurant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantListResponse) ProtoMessage() {}

func (x *RestaurantListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantpb_restaurant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantListResponse.ProtoReflect.Descriptor instead.
func (*RestaurantListResponse) Descriptor() ([]byte, []int) {
	return file_restaurantpb_restaurant_proto_rawDescGZIP(), []int{2}
}

func (x *RestaurantListResponse) GetRestaurants() []*Restaurant {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

type CreateRestaurantRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nombre          string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Direccion       string                 `protobuf:"bytes,3,opt,name=direccion,proto3" json:"direccion,omitempty"`
	Latitud         float64                `protobuf:"fixed64,4,opt,name=latitud,proto3" json:"latitud,omitempty"`
	Longitud        float64                `protobuf:"fixed64,5,opt,name=longitud,proto3" json:"longitud,omitempty"`
	Telefono        string                 `protobuf:"bytes,6,opt,name=telefono,proto3" json:"telefono,omitempty"`
	HorarioApertura string                 `protobuf:"bytes,7,opt,name=horario_apertura,json=horarioApertura,proto3" json:"horario_apertura,omitempty"`
	HorarioCierre   string                 `protobuf:"bytes,8,opt,name=horario_cierre,json=horarioCierre,proto3" json:"horario_cierre,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateRestaurantRequest) Reset() {
	*x = CreateRestaurantRequest{}
	mi := &file_restaurantpb_restaurant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRestaurantRequest) ProtoMessage() {}

func (x *CreateRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantpb_restaurant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRestaurantRequest.ProtoReflect.Descriptor instead.
func (*CreateRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_restaurantpb_restaurant_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRestaurantRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateRestaurantRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *CreateRestaurantRequest) GetDireccion() string {
	if x != nil {
		return x.Direccion
	}
	return ""
}

func (x *CreateRestaurantRequest) GetLatitud() float64 {
	if x != nil {
		return x.Latitud
	}
	return 0
}

func (x *CreateRestaurantRequest) GetLongitud() float64 {
	if x != nil {
		return x.Longitud
	}
	return 0
}

func (x *CreateRestaurantRequest) GetTelefono() string {
	if x != nil {
		return x.Telefono
	}
	return ""
}

func (x *CreateRestaurantRequest) GetHorarioApertura() string {
	if x != nil {
		return x.HorarioApertura
	}
	return ""
}

func (x *CreateRestaurantRequest) GetHorarioCierre() string {
	if x != nil {
		return x.HorarioCierre
	}
	return ""
}

type CreateRestaurantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestaurantId  int32                  `protobuf:"varint,1,opt,name=restaurant_id,json=restaurantId,proto3" json:"restaurant_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRestaurantResponse) Reset() {
	*x = CreateRestaurantResponse{}
	mi := &file_restaurantpb_restaurant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRestaurantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRestaurantResponse) ProtoMessage() {}

func (x *CreateRestaurantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantpb_restaurant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRestaurantResponse.ProtoReflect.Descriptor instead.
func (*CreateRestaurantResponse) Descriptor() ([]byte, []int) {
	return file_restaurantpb_restaurant_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRestaurantResponse) GetRestaurantId() int32 {
	if x != nil {
		return x.RestaurantId
	}
	return 0
}

func (x *CreateRestaurantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateRestaurantRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClienteId     int32                  `protobuf:"varint,1,opt,name=cliente_id,json=clienteId,proto3" json:"cliente_id,omitempty"`
	RestauranteId int32                  `protobuf:"varint,2,opt,name=restaurante_id,json=restauranteId,proto3" json:"restaurante_id,omitempty"`
	Estrellas     int32                  `protobuf:"varint,3,opt,name=estrellas,proto3" json:"estrellas,omitempty"`
	Comentario    string                 `protobuf:"bytes,4,opt,name=comentario,proto3" json:"comentario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRestaurantRatingRequest) Reset() {
	*x = CreateRestaurantRatingRequest{}
	mi := &file_restaurantpb_restaurant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRestaurantRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRestaurantRatingRequest) ProtoMessage() {}

func (x *CreateRestaurantRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantpb_restaurant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRestaurantRatingRequest.ProtoReflect.Descriptor instead.
func (*CreateRestaurantRatingRequest) Descriptor() ([]byte, []int) {
	return file_restaurantpb_restaurant_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRestaurantRatingRequest) GetClienteId() int32 {
	if x != nil {
		return x.ClienteId
	}
	return 0
}

func (x *CreateRestaurantRatingRequest) GetRestauranteId() int32 {
	if x != nil {
		return x.RestauranteId
	}
	return 0
}

func (x *CreateRestaurantRatingRequest) GetEstrellas() int32 {
	if x != nil {
		return x.Estrellas
	}
	return 0
}

func (x *CreateRestaurantRatingRequest) GetComentario() string {
	if x != nil {
		return x.Comentario
	}
	return ""
}

type CreateRestaurantRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RatingId      int32                  `protobuf:"varint,1,opt,name=rating_id,json=ratingId,proto3" json:"rating_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRestaurantRatingResponse) Reset() {
	*x = CreateRestaurantRatingResponse{}
	mi := &file_restaurantpb_restaurant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRestaurantRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRestaurantRatingResponse) ProtoMessage() {}

func (x *CreateRestaurantRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantpb_restaurant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRestaurantRatingResponse.ProtoReflect.Descriptor instead.
func (*CreateRestaurantRatingResponse) Descriptor() ([]byte, []int) {
	return file_restaurantpb_restaurant_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRestaurantRatingResponse) GetRatingId() int32 {
	if x != nil {
		return x.RatingId
	}
	return 0
}

func (x *CreateRestaurantRatingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetRestaurantRatingAverageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RestauranteId int32                  `protobuf:"varint,1,opt,name=restaurante_id,json=restauranteId,proto3" json:"restaurante_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantRatingAverageRequest) Reset() {
	*x = GetRestaurantRatingAverageRequest{}
	mi := &file_restaurantpb_restaurant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantRatingAverageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantRatingAverageRequest) ProtoMessage() {}

func (x *GetRestaurantRatingAverageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantpb_restaurant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantRatingAverageRequest.ProtoReflect.Descriptor instead.
func (*GetRestaurantRatingAverageRequest) Descriptor() ([]byte, []int) {
	return file_restaurantpb_restaurant_proto_rawDescGZIP(), []int{7}
}

func (x *GetRestaurantRatingAverageRequest) GetRestauranteId() int32 {
	if x != nil {
		return x.RestauranteId
	}
	return 0
}

type GetRestaurantRatingAverageResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Promedio            float64                `protobuf:"fixed64,1,opt,name=promedio,proto3" json:"promedio,omitempty"`
	TotalCalificaciones int32                  `protobuf:"varint,2,opt,name=total_calificaciones,json=totalCalificaciones,proto3" json:"total_calificaciones,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetRestaurantRatingAverageResponse) Reset() {
	*x = GetRestaurantRatingAverageResponse{}
	mi := &file_restaurantpb_restaurant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantRatingAverageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantRatingAverageResponse) ProtoMessage() {}

func (x *GetRestaurantRatingAverageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantpb_restaurant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantRatingAverageResponse.ProtoReflect.Descriptor instead.
func (*GetRestaurantRatingAverageResponse) Descriptor() ([]byte, []int) {
	return file_restaurantpb_restaurant_proto_rawDescGZIP(), []int{8}
}

func (x *GetRestaurantRatingAverageResponse) GetPromedio() float64 {
	if x != nil {
		return x.Promedio
	}
	return 0
}

func (x *GetRestaurantRatingAverageResponse) GetTotalCalificaciones() int32 {
	if x != nil {
		return x.TotalCalificaciones
	}
	return 0
}

type GetLatestRestaurantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestRestaurantsRequest) Reset() {
	*x = GetLatestRestaurantsRequest{}
	mi := &file_restaurantpb_restaurant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestRestaurantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestRestaurantsRequest) ProtoMessage() {}

func (x *GetLatestRestaurantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantpb_restaurant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestRestaurantsRequest.ProtoReflect.Descriptor instead.
func (*GetLatestRestaurantsRequest) Descriptor() ([]byte, []int) {
	return file_restaurantpb_restaurant_proto_rawDescGZIP(), []int{9}
}

func (x *GetLatestRestaurantsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTopRatedRestaurantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopRatedRestaurantsRequest) Reset() {
	*x = GetTopRatedRestaurantsRequest{}
	mi := &file_restaurantpb_restaurant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopRatedRestaurantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopRatedRestaurantsRequest) ProtoMessage() {}

func (x *GetTopRatedRestaurantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantpb_restaurant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopRatedRestaurantsRequest.ProtoReflect.Descriptor instead.
func (*GetTopRatedRestaurantsRequest) Descriptor() ([]byte, []int) {
	return file_restaurantpb_restaurant_proto_rawDescGZIP(), []int{10}
}

func (x *GetTopRatedRestaurantsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetRestaurantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Restaurants   []*Restaurant          `protobuf:"bytes,1,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRestaurantsResponse) Reset() {
	*x = GetRestaurantsResponse{}
	mi := &file_restaurantpb_restaurant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRestaurantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRestaurantsResponse) ProtoMessage() {}

func (x *GetRestaurantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_restaurantpb_restaurant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRestaurantsResponse.ProtoReflect.Descriptor instead.
func (*GetRestaurantsResponse) Descriptor() ([]byte, []int) {
	return file_restaurantpb_restaurant_proto_rawDescGZIP(), []int{11}
}

func (x *GetRestaurantsResponse) GetRestaurants() []*Restaurant {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

var File_restaurantpb_restaurant_proto protoreflect.FileDescriptor

const file_restaurantpb_restaurant_proto_rawDesc = "" +
	"\n" +
	"\x1drestaurantpb/restaurant.proto\x12\frestaurantpb\"\a\n" +
	"\x05Empty\"\xe0\x01\n" +
	"\n" +
	"Restaurant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x1c\n" +
	"\tdireccion\x18\x03 \x01(\tR\tdireccion\x12\x18\n" +
	"\alatitud\x18\x04 \x01(\x01R\alatitud\x12\x1a\n" +
	"\blongitud\x18\x05 \x01(\x01R\blongitud\x12\x1a\n" +
	"\btelefono\x18\x06 \x01(\tR\btelefono\x12\"\n" +
	"\fcalificacion\x18\a \x01(\x01R\fcalificacion\x12\x16\n" +
	"\x06activo\x18\b \x01(\bR\x06activo\"T\n" +
	"\x16RestaurantListResponse\x12:\n" +
	"\vrestaurants\x18\x01 \x03(\v2\x18.restaurantpb.RestaurantR\vrestaurants\"\x8c\x02\n" +
	"\x17CreateRestaurantRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x1c\n" +
	"\tdireccion\x18\x03 \x01(\tR\tdireccion\x12\x18\n" +
	"\alatitud\x18\x04 \x01(\x01R\alatitud\x12\x1a\n" +
	"\blongitud\x18\x05 \x01(\x01R\blongitud\x12\x1a\n" +
	"\btelefono\x18\x06 \x01(\tR\btelefono\x12)\n" +
	"\x10horario_apertura\x18\a \x01(\tR\x0fhorarioApertura\x12%\n" +
	"\x0ehorario_cierre\x18\b \x01(\tR\rhorarioCierre\"Y\n" +
	"\x18CreateRestaurantResponse\x12#\n" +
	"\rrestaurant_id\x18\x01 \x01(\x05R\frestaurantId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa3\x01\n" +
	"\x1dCreateRestaurantRatingRequest\x12\x1d\n" +
	"\n" +
	"cliente_id\x18\x01 \x01(\x05R\tclienteId\x12%\n" +
	"\x0erestaurante_id\x18\x02 \x01(\x05R\rrestauranteId\x12\x1c\n" +
	"\testrellas\x18\x03 \x01(\x05R\testrellas\x12\x1e\n" +
	"\n" +
	"comentario\x18\x04 \x01(\tR\n" +
	"comentario\"W\n" +
	"\x1eCreateRestaurantRatingResponse\x12\x1b\n" +
	"\trating_id\x18\x01 \x01(\x05R\bratingId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"J\n" +
	"!GetRestaurantRatingAverageRequest\x12%\n" +
	"\x0erestaurante_id\x18\x01 \x01(\x05R\rrestauranteId\"s\n" +
	"\"GetRestaurantRatingAverageResponse\x12\x1a\n" +
	"\bpromedio\x18\x01 \x01(\x01R\bpromedio\x121\n" +
	"\x14total_calificaciones\x18\x02 \x01(\x05R\x13totalCalificaciones\"3\n" +
	"\x1bGetLatestRestaurantsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"5\n" +
	"\x1dGetTopRatedRestaurantsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"T\n" +
	"\x16GetRestaurantsResponse\x12:\n" +
	"\vrestaurants\x18\x01 \x03(\v2\x18.restaurantpb.RestaurantR\vrestaurants2\x90\x05\n" +
	"\x11RestaurantService\x12L\n" +
	"\x0fListRestaurants\x12\x13.restaurantpb.Empty\x1a$.restaurantpb.RestaurantListResponse\x12a\n" +
	"\x10CreateRestaurant\x12%.restaurantpb.CreateRestaurantRequest\x1a&.restaurantpb.CreateRestaurantResponse\x12s\n" +
	"\x16CreateRestaurantRating\x12+.restaurantpb.CreateRestaurantRatingRequest\x1a,.restaurantpb.CreateRestaurantRatingResponse\x12\x7f\n" +
	"\x1aGetRestaurantRatingAverage\x12/.restaurantpb.GetRestaurantRatingAverageRequest\x1a0.restaurantpb.GetRestaurantRatingAverageResponse\x12g\n" +
	"\x14GetLatestRestaurants\x12).restaurantpb.GetLatestRestaurantsRequest\x1a$.restaurantpb.GetRestaurantsResponse\x12k\n" +
	"\x16GetTopRatedRestaurants\x12+.restaurantpb.GetTopRatedRestaurantsRequest\x1a$.restaurantpb.GetRestaurantsResponseB\x1dZ\x1bdelivery-proto/restaurantpbb\x06proto3"

var (
	file_restaurantpb_restaurant_proto_rawDescOnce sync.Once
	file_restaurantpb_restaurant_proto_rawDescData []byte
)

func file_restaurantpb_restaurant_proto_rawDescGZIP() []byte {
	file_restaurantpb_restaurant_proto_rawDescOnce.Do(func() {
		file_restaurantpb_restaurant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_restaurantpb_restaurant_proto_rawDesc), len(file_restaurantpb_restaurant_proto_rawDesc)))
	})
	return file_restaurantpb_restaurant_proto_rawDescData
}

var file_restaurantpb_restaurant_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_restaurantpb_restaurant_proto_goTypes = []any{
	(*Empty)(nil),                              // 0: restaurantpb.Empty
	(*Restaurant)(nil),                         // 1: restaurantpb.Restaurant
	(*RestaurantListResponse)(nil),             // 2: restaurantpb.RestaurantListResponse
	(*CreateRestaurantRequest)(nil),            // 3: restaurantpb.CreateRestaurantRequest
	(*CreateRestaurantResponse)(nil),           // 4: restaurantpb.CreateRestaurantResponse
	(*CreateRestaurantRatingRequest)(nil),      // 5: restaurantpb.CreateRestaurantRatingRequest
	(*CreateRestaurantRatingResponse)(nil),     // 6: restaurantpb.CreateRestaurantRatingResponse
	(*GetRestaurantRatingAverageRequest)(nil),  // 7: restaurantpb.GetRestaurantRatingAverageRequest
	(*GetRestaurantRatingAverageResponse)(nil), // 8: restaurantpb.GetRestaurantRatingAverageResponse
	(*GetLatestRestaurantsRequest)(nil),        // 9: restaurantpb.GetLatestRestaurantsRequest
	(*GetTopRatedRestaurantsRequest)(nil),      // 10: restaurantpb.GetTopRatedRestaurantsRequest
	(*GetRestaurantsResponse)(nil),             // 11: restaurantpb.GetRestaurantsResponse
}
var file_restaurantpb_restaurant_proto_depIdxs = []int32{
	1,  // 0: restaurantpb.RestaurantListResponse.restaurants:type_name -> restaurantpb.Restaurant
	1,  // 1: restaurantpb.GetRestaurantsResponse.restaurants:type_name -> restaurantpb.Restaurant
	0,  // 2: restaurantpb.RestaurantService.ListRestaurants:input_type -> restaurantpb.Empty
	3,  // 3: restaurantpb.RestaurantService.CreateRestaurant:input_type -> restaurantpb.CreateRestaurantRequest
	5,  // 4: restaurantpb.RestaurantService.CreateRestaurantRating:input_type -> restaurantpb.CreateRestaurantRatingRequest
	7,  // 5: restaurantpb.RestaurantService.GetRestaurantRatingAverage:input_type -> restaurantpb.GetRestaurantRatingAverageRequest
	9,  // 6: restaurantpb.RestaurantService.GetLatestRestaurants:input_type -> restaurantpb.GetLatestRestaurantsRequest
	10, // 7: restaurantpb.RestaurantService.GetTopRatedRestaurants:input_type -> restaurantpb.GetTopRatedRestaurantsRequest
	2,  // 8: restaurantpb.RestaurantService.ListRestaurants:output_type -> restaurantpb.RestaurantListResponse
	4,  // 9: restaurantpb.RestaurantService.CreateRestaurant:output_type -> restaurantpb.CreateRestaurantResponse
	6,  // 10: restaurantpb.RestaurantService.CreateRestaurantRating:output_type -> restaurantpb.CreateRestaurantRatingResponse
	8,  // 11: restaurantpb.RestaurantService.GetRestaurantRatingAverage:output_type -> restaurantpb.GetRestaurantRatingAverageResponse
	11, // 12: restaurantpb.RestaurantService.GetLatestRestaurants:output_type -> restaurantpb.GetRestaurantsResponse
	11, // 13: restaurantpb.RestaurantService.GetTopRatedRestaurants:output_type -> restaurantpb.GetRestaurantsResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_restaurantpb_restaurant_proto_init() }
func file_restaurantpb_restaurant_proto_init() {
	if File_restaurantpb_restaurant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_restaurantpb_restaurant_proto_rawDesc), len(file_restaurantpb_restaurant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_restaurantpb_restaurant_proto_goTypes,
		DependencyIndexes: file_restaurantpb_restaurant_proto_depIdxs,
		MessageInfos:      file_restaurantpb_restaurant_proto_msgTypes,
	}.Build()
	File_restaurantpb_restaurant_proto = out.File
	file_restaurantpb_restaurant_proto_goTypes = nil
	file_restaurantpb_restaurant_proto_depIdxs = nil
}
