// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: restaurant.proto

package restaurantpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RestaurantServiceClient is the client API for RestaurantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RestaurantServiceClient interface {
	ListRestaurants(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RestaurantListResponse, error)
	CreateRestaurant(ctx context.Context, in *CreateRestaurantRequest, opts ...grpc.CallOption) (*CreateRestaurantResponse, error)
	CreateRestaurantRating(ctx context.Context, in *CreateRestaurantRatingRequest, opts ...grpc.CallOption) (*CreateRestaurantRatingResponse, error)
	GetRestaurantRatingAverage(ctx context.Context, in *GetRestaurantRatingAverageRequest, opts ...grpc.CallOption) (*GetRestaurantRatingAverageResponse, error)
	GetLatestRestaurants(ctx context.Context, in *GetLatestRestaurantsRequest, opts ...grpc.CallOption) (*GetRestaurantsResponse, error)
	GetTopRatedRestaurants(ctx context.Context, in *GetTopRatedRestaurantsRequest, opts ...grpc.CallOption) (*GetRestaurantsResponse, error)
	// Promociones
	CreatePromocion(ctx context.Context, in *CreatePromocionRequest, opts ...grpc.CallOption) (*CreatePromocionResponse, error)
	GetPromociones(ctx context.Context, in *GetPromocionesRequest, opts ...grpc.CallOption) (*GetPromocionesResponse, error)
	UpdatePromocion(ctx context.Context, in *UpdatePromocionRequest, opts ...grpc.CallOption) (*UpdatePromocionResponse, error)
	// Cupones
	CreateCupon(ctx context.Context, in *CreateCuponRequest, opts ...grpc.CallOption) (*CreateCuponResponse, error)
	GetCupones(ctx context.Context, in *GetCuponesRequest, opts ...grpc.CallOption) (*GetCuponesResponse, error)
	UpdateCupon(ctx context.Context, in *UpdateCuponRequest, opts ...grpc.CallOption) (*UpdateCuponResponse, error)
	AutorizarCupon(ctx context.Context, in *AutorizarCuponRequest, opts ...grpc.CallOption) (*AutorizarCuponResponse, error)
}

type restaurantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRestaurantServiceClient(cc grpc.ClientConnInterface) RestaurantServiceClient {
	return &restaurantServiceClient{cc}
}

func (c *restaurantServiceClient) ListRestaurants(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RestaurantListResponse, error) {
	out := new(RestaurantListResponse)
	err := c.cc.Invoke(ctx, "/restaurantpb.RestaurantService/ListRestaurants", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) CreateRestaurant(ctx context.Context, in *CreateRestaurantRequest, opts ...grpc.CallOption) (*CreateRestaurantResponse, error) {
	out := new(CreateRestaurantResponse)
	err := c.cc.Invoke(ctx, "/restaurantpb.RestaurantService/CreateRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) CreateRestaurantRating(ctx context.Context, in *CreateRestaurantRatingRequest, opts ...grpc.CallOption) (*CreateRestaurantRatingResponse, error) {
	out := new(CreateRestaurantRatingResponse)
	err := c.cc.Invoke(ctx, "/restaurantpb.RestaurantService/CreateRestaurantRating", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) GetRestaurantRatingAverage(ctx context.Context, in *GetRestaurantRatingAverageRequest, opts ...grpc.CallOption) (*GetRestaurantRatingAverageResponse, error) {
	out := new(GetRestaurantRatingAverageResponse)
	err := c.cc.Invoke(ctx, "/restaurantpb.RestaurantService/GetRestaurantRatingAverage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) GetLatestRestaurants(ctx context.Context, in *GetLatestRestaurantsRequest, opts ...grpc.CallOption) (*GetRestaurantsResponse, error) {
	out := new(GetRestaurantsResponse)
	err := c.cc.Invoke(ctx, "/restaurantpb.RestaurantService/GetLatestRestaurants", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) GetTopRatedRestaurants(ctx context.Context, in *GetTopRatedRestaurantsRequest, opts ...grpc.CallOption) (*GetRestaurantsResponse, error) {
	out := new(GetRestaurantsResponse)
	err := c.cc.Invoke(ctx, "/restaurantpb.RestaurantService/GetTopRatedRestaurants", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) CreatePromocion(ctx context.Context, in *CreatePromocionRequest, opts ...grpc.CallOption) (*CreatePromocionResponse, error) {
	out := new(CreatePromocionResponse)
	err := c.cc.Invoke(ctx, "/restaurantpb.RestaurantService/CreatePromocion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) GetPromociones(ctx context.Context, in *GetPromocionesRequest, opts ...grpc.CallOption) (*GetPromocionesResponse, error) {
	out := new(GetPromocionesResponse)
	err := c.cc.Invoke(ctx, "/restaurantpb.RestaurantService/GetPromociones", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) UpdatePromocion(ctx context.Context, in *UpdatePromocionRequest, opts ...grpc.CallOption) (*UpdatePromocionResponse, error) {
	out := new(UpdatePromocionResponse)
	err := c.cc.Invoke(ctx, "/restaurantpb.RestaurantService/UpdatePromocion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) CreateCupon(ctx context.Context, in *CreateCuponRequest, opts ...grpc.CallOption) (*CreateCuponResponse, error) {
	out := new(CreateCuponResponse)
	err := c.cc.Invoke(ctx, "/restaurantpb.RestaurantService/CreateCupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) GetCupones(ctx context.Context, in *GetCuponesRequest, opts ...grpc.CallOption) (*GetCuponesResponse, error) {
	out := new(GetCuponesResponse)
	err := c.cc.Invoke(ctx, "/restaurantpb.RestaurantService/GetCupones", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) UpdateCupon(ctx context.Context, in *UpdateCuponRequest, opts ...grpc.CallOption) (*UpdateCuponResponse, error) {
	out := new(UpdateCuponResponse)
	err := c.cc.Invoke(ctx, "/restaurantpb.RestaurantService/UpdateCupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) AutorizarCupon(ctx context.Context, in *AutorizarCuponRequest, opts ...grpc.CallOption) (*AutorizarCuponResponse, error) {
	out := new(AutorizarCuponResponse)
	err := c.cc.Invoke(ctx, "/restaurantpb.RestaurantService/AutorizarCupon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestaurantServiceServer is the server API for RestaurantService service.
// All implementations should embed UnimplementedRestaurantServiceServer
// for forward compatibility
type RestaurantServiceServer interface {
	ListRestaurants(context.Context, *Empty) (*RestaurantListResponse, error)
	CreateRestaurant(context.Context, *CreateRestaurantRequest) (*CreateRestaurantResponse, error)
	CreateRestaurantRating(context.Context, *CreateRestaurantRatingRequest) (*CreateRestaurantRatingResponse, error)
	GetRestaurantRatingAverage(context.Context, *GetRestaurantRatingAverageRequest) (*GetRestaurantRatingAverageResponse, error)
	GetLatestRestaurants(context.Context, *GetLatestRestaurantsRequest) (*GetRestaurantsResponse, error)
	GetTopRatedRestaurants(context.Context, *GetTopRatedRestaurantsRequest) (*GetRestaurantsResponse, error)
	// Promociones
	CreatePromocion(context.Context, *CreatePromocionRequest) (*CreatePromocionResponse, error)
	GetPromociones(context.Context, *GetPromocionesRequest) (*GetPromocionesResponse, error)
	UpdatePromocion(context.Context, *UpdatePromocionRequest) (*UpdatePromocionResponse, error)
	// Cupones
	CreateCupon(context.Context, *CreateCuponRequest) (*CreateCuponResponse, error)
	GetCupones(context.Context, *GetCuponesRequest) (*GetCuponesResponse, error)
	UpdateCupon(context.Context, *UpdateCuponRequest) (*UpdateCuponResponse, error)
	AutorizarCupon(context.Context, *AutorizarCuponRequest) (*AutorizarCuponResponse, error)
}

// UnimplementedRestaurantServiceServer should be embedded to have forward compatible implementations.
type UnimplementedRestaurantServiceServer struct {
}

func (UnimplementedRestaurantServiceServer) ListRestaurants(context.Context, *Empty) (*RestaurantListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRestaurants not implemented")
}
func (UnimplementedRestaurantServiceServer) CreateRestaurant(context.Context, *CreateRestaurantRequest) (*CreateRestaurantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRestaurant not implemented")
}
func (UnimplementedRestaurantServiceServer) CreateRestaurantRating(context.Context, *CreateRestaurantRatingRequest) (*CreateRestaurantRatingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRestaurantRating not implemented")
}
func (UnimplementedRestaurantServiceServer) GetRestaurantRatingAverage(context.Context, *GetRestaurantRatingAverageRequest) (*GetRestaurantRatingAverageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRestaurantRatingAverage not implemented")
}
func (UnimplementedRestaurantServiceServer) GetLatestRestaurants(context.Context, *GetLatestRestaurantsRequest) (*GetRestaurantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestRestaurants not implemented")
}
func (UnimplementedRestaurantServiceServer) GetTopRatedRestaurants(context.Context, *GetTopRatedRestaurantsRequest) (*GetRestaurantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopRatedRestaurants not implemented")
}
func (UnimplementedRestaurantServiceServer) CreatePromocion(context.Context, *CreatePromocionRequest) (*CreatePromocionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePromocion not implemented")
}
func (UnimplementedRestaurantServiceServer) GetPromociones(context.Context, *GetPromocionesRequest) (*GetPromocionesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPromociones not implemented")
}
func (UnimplementedRestaurantServiceServer) UpdatePromocion(context.Context, *UpdatePromocionRequest) (*UpdatePromocionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePromocion not implemented")
}
func (UnimplementedRestaurantServiceServer) CreateCupon(context.Context, *CreateCuponRequest) (*CreateCuponResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCupon not implemented")
}
func (UnimplementedRestaurantServiceServer) GetCupones(context.Context, *GetCuponesRequest) (*GetCuponesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCupones not implemented")
}
func (UnimplementedRestaurantServiceServer) UpdateCupon(context.Context, *UpdateCuponRequest) (*UpdateCuponResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCupon not implemented")
}
func (UnimplementedRestaurantServiceServer) AutorizarCupon(context.Context, *AutorizarCuponRequest) (*AutorizarCuponResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AutorizarCupon not implemented")
}

// UnsafeRestaurantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RestaurantServiceServer will
// result in compilation errors.
type UnsafeRestaurantServiceServer interface {
	mustEmbedUnimplementedRestaurantServiceServer()
}

func RegisterRestaurantServiceServer(s grpc.ServiceRegistrar, srv RestaurantServiceServer) {
	s.RegisterService(&RestaurantService_ServiceDesc, srv)
}

func _RestaurantService_ListRestaurants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).ListRestaurants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurantpb.RestaurantService/ListRestaurants",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).ListRestaurants(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_CreateRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).CreateRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurantpb.RestaurantService/CreateRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).CreateRestaurant(ctx, req.(*CreateRestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_CreateRestaurantRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRestaurantRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).CreateRestaurantRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurantpb.RestaurantService/CreateRestaurantRating",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).CreateRestaurantRating(ctx, req.(*CreateRestaurantRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_GetRestaurantRatingAverage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestaurantRatingAverageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).GetRestaurantRatingAverage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurantpb.RestaurantService/GetRestaurantRatingAverage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).GetRestaurantRatingAverage(ctx, req.(*GetRestaurantRatingAverageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_GetLatestRestaurants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestRestaurantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).GetLatestRestaurants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurantpb.RestaurantService/GetLatestRestaurants",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).GetLatestRestaurants(ctx, req.(*GetLatestRestaurantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_GetTopRatedRestaurants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopRatedRestaurantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).GetTopRatedRestaurants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurantpb.RestaurantService/GetTopRatedRestaurants",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).GetTopRatedRestaurants(ctx, req.(*GetTopRatedRestaurantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_CreatePromocion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePromocionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).CreatePromocion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurantpb.RestaurantService/CreatePromocion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).CreatePromocion(ctx, req.(*CreatePromocionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_GetPromociones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPromocionesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).GetPromociones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurantpb.RestaurantService/GetPromociones",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).GetPromociones(ctx, req.(*GetPromocionesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_UpdatePromocion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePromocionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).UpdatePromocion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurantpb.RestaurantService/UpdatePromocion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).UpdatePromocion(ctx, req.(*UpdatePromocionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_CreateCupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCuponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).CreateCupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurantpb.RestaurantService/CreateCupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).CreateCupon(ctx, req.(*CreateCuponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_GetCupones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCuponesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).GetCupones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurantpb.RestaurantService/GetCupones",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).GetCupones(ctx, req.(*GetCuponesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_UpdateCupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCuponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).UpdateCupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurantpb.RestaurantService/UpdateCupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).UpdateCupon(ctx, req.(*UpdateCuponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_AutorizarCupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutorizarCuponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).AutorizarCupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurantpb.RestaurantService/AutorizarCupon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).AutorizarCupon(ctx, req.(*AutorizarCuponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RestaurantService_ServiceDesc is the grpc.ServiceDesc for RestaurantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RestaurantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "restaurantpb.RestaurantService",
	HandlerType: (*RestaurantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRestaurants",
			Handler:    _RestaurantService_ListRestaurants_Handler,
		},
		{
			MethodName: "CreateRestaurant",
			Handler:    _RestaurantService_CreateRestaurant_Handler,
		},
		{
			MethodName: "CreateRestaurantRating",
			Handler:    _RestaurantService_CreateRestaurantRating_Handler,
		},
		{
			MethodName: "GetRestaurantRatingAverage",
			Handler:    _RestaurantService_GetRestaurantRatingAverage_Handler,
		},
		{
			MethodName: "GetLatestRestaurants",
			Handler:    _RestaurantService_GetLatestRestaurants_Handler,
		},
		{
			MethodName: "GetTopRatedRestaurants",
			Handler:    _RestaurantService_GetTopRatedRestaurants_Handler,
		},
		{
			MethodName: "CreatePromocion",
			Handler:    _RestaurantService_CreatePromocion_Handler,
		},
		{
			MethodName: "GetPromociones",
			Handler:    _RestaurantService_GetPromociones_Handler,
		},
		{
			MethodName: "UpdatePromocion",
			Handler:    _RestaurantService_UpdatePromocion_Handler,
		},
		{
			MethodName: "CreateCupon",
			Handler:    _RestaurantService_CreateCupon_Handler,
		},
		{
			MethodName: "GetCupones",
			Handler:    _RestaurantService_GetCupones_Handler,
		},
		{
			MethodName: "UpdateCupon",
			Handler:    _RestaurantService_UpdateCupon_Handler,
		},
		{
			MethodName: "AutorizarCupon",
			Handler:    _RestaurantService_AutorizarCupon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "restaurant.proto",
}
