apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deliver-eats-ingress
  namespace: deliver-eats
  annotations:
    kubernetes.io/ingress.class: gce
    kubernetes.io/ingress.allow-http: "true"
    networking.gke.io/managed-certificates: deliver-eats-dev-cert
spec:
  ingressClassName: gce
  rules:
    - host: dev.delivereats.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
